export const GLOBAL_ACHIEVEMENTS = {
  ANCIENT_TECHNOLOGY_1: "Ancient Technology 1",
  ANCIENT_TECHNOLOGY_2: "Ancient Technology 2",
  ANCIENT_TECHNOLOGY_3: "Ancient Technology 3",
  ANCIENT_TECHNOLOGY_4: "Ancient Technology 4",
  ANCIENT_TECHNOLOGY_5: "Ancient Technology 5",
  ANNIHILATION_OF_THE_ORDER: "Annihilation of the Order",
  ARTIFACT_RECOVERED: "Artifact: Recovered",
  ARTIFACT_LOST: "Artifact: Lost",
  ARTIFACT_CLEANSED: "Artifact: Cleansed",
  CITY_RULE_MILITARISTIC: "City Rule: Militaristic",
  CITY_RULE_ECONOMIC: "City Rule: Economic",
  CITY_RULE_DEMONIC: "City Rule: Demonic",
  END_OF_THE_INVASION: "End of the Invasion",
  END_OF_CORRUPTION_1: "End of Corruption 1",
  END_OF_CORRUPTION_2: "End of Corruption 2",
  END_OF_CORRUPTION_3: "End of Corruption 3",
  END_OF_GLOOM: "End of Gloom",
  THE_DRAKE_SLAIN: "The Drake Slain",
  THE_DRAKE_AIDED: "The Drake Aided",
  THE_DEAD_INVADE: "The Dead Invade",
  THE_DEMON_DETHRONED: "The Demon Dethroned",
  THE_EDGE_OF_DARKNESS: "The Edge of Darkness",
  THE_MERCHANT_FLEES: "The Merchant Flees",
  THE_POWER_OF_ENHANCEMENT: "The Power of Enhancement",
  THE_RIFT_CLOSED: "The Rift Closed",
  THE_RIFT_NEUTRALIZED: "The Rift Neutralized",
  THE_VOICE_SILENCED: "The Voice: Silenced",
  THE_VOICE_FREED: "The Voice: Freed",
  WATER_BREATHING: "Water-Breathing",

  // Forgotten Circles
  THROUGH_THE_PORTAL: "Through the Portal",
  SEVERED_TIES: "Severed Ties",
  KNOWLEDGE_IS_POWER_1: "Knowledge is Power 1",
  KNOWLEDGE_IS_POWER_2: "Knowledge is Power 2",
  KNOWLEDGE_IS_POWER_3: "Knowledge is Power 3",
  KNOWLEDGE_IS_POWER_4: "Knowledge is Power 4",
  PERIL_ADVERTED_1: "Peril Adverted 1",
  PERIL_ADVERTED_2: "Peril Adverted 2",
  PERIL_ADVERTED_3: "Peril Adverted 3",
  PERIL_ADVERTED_4: "Peril Adverted 4",
  PIECES_OF_AN_ARTIFACT_1: "Pieces of an Artifact 1",
  PIECES_OF_AN_ARTIFACT_2: "Pieces of an Artifact 2",
  PIECES_OF_AN_ARTIFACT_3: "Pieces of an Artifact 3",
  MECHANICAL_SPLENDOR: "Mechanical Splendor",
};
